services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "3500:3500"
    # container_name: backend_2_cont
    restart: always
    environment:
      - MONGODB_URL=${DB_URL}
    volumes:
      - backend_data_2:/app/data
    networks:
      - my_network1


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_cont
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network1

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro,rslave
      - /sys:/host/sys:ro,rslave
      - /:/rootfs:ro,rslave
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.powersupplyclass'
    ports:
      - "9100:9100"
    networks:
      - my_network1

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_service
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - my_network1

  alertmanager:
    image: prom/alertmanager:latest
    restart: always
    container_name: alertmgr
    ports:
      - "9093:9093"
    volumes:
      - "./alert-manager:/config"
      - alert-manager-data:/data
    command:
      - '--config.file=/config/alertmanager.yaml'
      - '--log.level=debug'
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - my_network1
    
  nginx:
    image: nginx:latest
    ports:
      - "3500:80"  # Expose NGINX on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom NGINX config
    networks:
      - my_network1
    restart: always
    

volumes:
  backend_data_2: {}
  prometheus-data: {}
  alert-manager-data: {}
  nginx.conf: {}

networks:
  my_network1: {}
