services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_cont-1
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my_network1

networks:
  my_network1: {}
