# route:
#   group_by: ['alertname']
#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 1m
#   receiver: 'send_email'
# receivers:
#   - name: 'send_email'
#     email_configs:
#       - to: sdakwoji@gmail.com
#         from: omenormanagement@gmail.com
#         smarthost: smtp.gmail.com:465
#         auth_username: omenormanagement@gmail.com
#         auth_password: jegoogwpcqtmzfah 
#         require_tls: false



        
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']

global:
  resolve_timeout: 5m

receivers:
  - name: 'send_email'
    email_configs:
      - to: 'sdakwoji@gmail.com'
        from: 'omenormanagement@gmail.com'
        smarthost: 'smtp.gmail.com:465'
        auth_username: 'omenormanagement@gmail.com'
        auth_password: 'jegoogwpcqtmzfah'
        require_tls: true  # Changed to true for security
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://localhost:5000/alert'  # Ensure this points to the webhook service

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'webhook-receiver'  # Default receiver

  routes:
    - match:
        severity: 'critical'
      receiver: 'send_email'
      repeat_interval: 1m  # Faster notification for critical alerts

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
